services:
  db:
    image: mariadb:latest
    container_name: yourls-db
    restart: always
    ports:
      - "33308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yourls
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./db/data:/var/lib/mysql

  app:
    build: .
    container_name: yourls
    restart: always
    ports:
      - "3008:80"
    env_file:
      - .env
    environment:
      YOURLS_SITE: ${APP_URL}
      YOURLS_USER: admin
      YOURLS_PASS: admin
      YOURLS_DB_HOST: db
      YOURLS_DB_USER: root
      YOURLS_DB_PASS: root
      YOURLS_DB_NAME: yourls
    volumes:
      - ./user/plugins/usrv/assets/srv.php:/var/www/html/user/pages/srv.php
      - ./user/plugins/iqrcodes/assets/qrchhk.php:/var/www/html/user/pages/qrchhk.php
      - ./user/config.php:/var/www/html/user/config.php
      - ./user/plugins/iqrcodes:/var/www/html/user/plugins/iqrcodes
      - ./user/plugins/usrv:/var/www/html/user/plugins/usrv
      - ./user/plugins/oidc:/var/www/html/user/plugins/oidc
    depends_on:
      - db
    links:
      - db
